/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"


void
add_prog_1(char *host, int x, int y)// ADDED ******
{
	CLIENT *clnt;
	int  *result_1;
	numbers  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "tcp"); // ADDED ******
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	add_1_arg.a = x; // ADDED ******
	add_1_arg.b = y; // ADDED ******

	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		fprintf(stderr, "result_1 = %d\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	// ADDED ******
	if (argc < 4) {
		printf ("usage: %s server_host NUMBER1 NUMBER2\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	// ADDED ******
	add_prog_1 (host, atoi(argv[2]), atoi(argv[3]));
exit (0);
}
